baseURL = 'https://thesecurityvault.com'
languageCode = 'en-us'
title = 'The Security Vault'
theme = '4.0'
copyright = "Copyright 2019-{year} The Security Vault. All rights reserved."
enableRobotsTXT = true
postsFolder = 'posts'

[params]
  author = 'Luis Fontes'
  images = ["/banner.png"]
  description = "Because Security Matters - Demistifying those weird and dark security vulnerabilities nobody talks about"
  mainSections = ['post']

  # Theme specific configs
  logo = '/img/logo.png'
  ads_title = "My Projects"
  social_title = "Social"
  author_on_posts = false


# category and tag are default in hugo
# overriding it just for doc and control
[taxonomies]
  category = 'category'
  tag = 'tag'

[permalinks]
  posts = "/:title"
  categories = "/:slug/"

[urlRewrite]
"/category/(.*?)/(.*)" = "/$1/$2"


# change index.xml to feed.xml
[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"


#https://gohugo.io/functions/highlight/
#https://xyproto.github.io/splash/docs/
[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'tango'
    tabWidth = 4

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 5
  # [[menu.main]]
  #   identifier = 'appsec'
  #   name = 'Appllication Security'
  #   url = '/category/appsec/'
  #   weight = 10
  # [[menu.main]]
  #   identifier = 'pentest'
  #   name = 'Pentest'
  #   url = '/category/pentest/'
  #  weight = 20
  [[menu.main]]
    identifier = 'aboutme'
    name = 'About me'
    url = '/about/'
    weight = 30

  [[menu.social]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/luisfontes19'
  [[menu.social]]
    identifier = 'rss'
    name = 'Rss'
    url = 'https://thesecurityvault.com/?feed=rss2'
  
  [[menu.ads]]
    identifier = '1-XXExploiter'
    url = 'https://github.com/luisfontes19/xxexploiter'
    pre = 'https://raw.githubusercontent.com/luisfontes19/xxexploiter/master/banner.png'
  [[menu.ads]]
    identifier = '2-Swissknife'
    url = 'https://marketplace.visualstudio.com/items?itemName=luisfontes19.vscode-swissknife'
    pre = 'https://github.com/luisfontes19/vscode-swissknife/raw/master/data/swissknife_banner.png'
  [[menu.ads]]
    identifier = '3-CSRFER'
    url = 'https://github.com/luisfontes19/CSRFER'
    pre = '/img/csrfer'
  [[menu.ads]]
    identifier = '4-SharpCorsProxy'
    url = 'https://github.com/luisfontes19/SharpCorsProxy'
    pre = 'https://raw.githubusercontent.com/luisfontes19/SharpCorsProxy/master/SharpCorsProxy.png'
  [[menu.ads]]
    identifier = '5-DamnVulnerableCryptoApp'
    url = 'https://github.com/DamnVulnerableCryptoApp/DamnVulnerableCryptoApp'
    pre = 'https://raw.githubusercontent.com/DamnVulnerableCryptoApp/DamnVulnerableCryptoApp/master/frontend/src/Images/logo.png'
  
    
